### PR TITLE
Add new videos in webp format

### PR DESCRIPTION
**Pull request by louislang**

### CODE REVIEW

**Review by maxrake — APPROVED** [review]
These new videos are a bit grainy and the text is slightly smaller than the other videos on the page...but overall not different enough from them to disapprove.

A possible improvement...if it is possible with the `.webp` format...is to "pause" on the end of the animation loop so viewers can see the results of the commands before the loop starts again.

**Comment by furi0us333** [comment]
The `init` command has changed slightly with the addition of multi-lockfile support. I will let you decide if it is worth re-recording for that.

**Comment by louislang** [comment]
@maxrake @furi0us333 @cd-work updated the videos to the new, better encoding @andreaphylum provided! If this looks good, it should be good to merge.

**Review by furi0us333 — APPROVED** [review]

**Comment by furi0us333** [comment]
Merging - they look good to me.

**Pull request merged**
